# Generated by Django 4.1.3 on 2022-11-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('date_of_record', models.DateField()),
                ('No_of_samples', models.IntegerField()),
                ('no_of_deaths', models.IntegerField()),
                ('no_of_positive', models.IntegerField()),
                ('no_of_negative', models.IntegerField()),
                ('no_of_discharged', models.IntegerField()),
            ],
        ),
    ]
